using IronPython.Hosting;
using Microsoft.Scripting.Hosting;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ETL_Controller
{
    public class PythonInterpreter
    {
        //Method taking from the link below.
        //https://medium.com/emoney-engineering/running-python-script-from-c-and-working-with-the-results-843e68d230e5
        public string PatchParameter(string pythonScriptPath, string parameter, int serviceid)
        {
            var engine = Python.CreateEngine(); // Extract Python language engine from their grasp
            var scope = engine.CreateScope(); // Introduce Python namespace (scope)
            var d = new Dictionary<string, object>
            {
                { "serviceid", serviceid},
                { "parameter", parameter}
            }; // Add some sample parameters. Notice that there is no need in specifically setting the object type, interpreter will do that part for us in the script properly with high probability

            scope.SetVariable("params", d); // This will be the name of the dictionary in python script, initialized with previously created .NET Dictionary
            ScriptSource source = engine.CreateScriptSourceFromFile(pythonScriptPath); // Load the script
            object result = source.Execute(scope);
            parameter = scope.GetVariable<string>("parameter"); // To get the finally set variable 'parameter' from the python script
            return parameter;
        }

        //blur_blur_IMG_20180423_122036
        public string RunCmd(string cmd, string args)
        {
            ProcessStartInfo start = new ProcessStartInfo();


            start.FileName = @"C:\Users\Chris\Anaconda3\python.exe";
            start.Arguments = string.Format("\"{0}\" \"{1}\"", cmd, args);
            start.UseShellExecute = false;// Do not use OS shell
            start.CreateNoWindow = false; // We do need new window
            start.RedirectStandardOutput = true;// Any output, generated by application will be redirected back
            start.RedirectStandardError = true; // Any error in standard output will be redirected back (for example exceptions)
            using (Process process = Process.Start(start))
            {
                using (StreamReader reader = process.StandardOutput)
                {
                    string stderr = process.StandardError.ReadToEnd(); // Here are the exceptions from our Python script
                    string result = reader.ReadToEnd(); // Here is the result of StdOut(for example: print "test")
                    return result;
                }
            }
        }

        public void run_cmd(string fileName)
        {

            fileName = @"C:\Users\Chris\Source\Repos\UCN-4-Semester-Project---Group-7\TrashDetector\ImageRegonition\predictBatchFromStageDB.py";


            Process p = new Process();
            p.StartInfo = new ProcessStartInfo(@"C:\Users\Chris\Anaconda3\python.exe", fileName)
            {
                RedirectStandardOutput = true,
                UseShellExecute = false,
                CreateNoWindow = false
            };
            Console.WriteLine("stating");
            p.Start();

            string output = p.StandardOutput.ReadToEnd();
            p.WaitForExit();

            Console.WriteLine(output);

            Console.WriteLine("finished");

            Console.ReadLine();
        }
    }
}
